In [1]:
import matplotlib.pyplot as plt
import scipy
from scipy import stats
from scipy.stats import norm
import pandas as pd
import numpy as np
import seaborn as sns
from statsmodels.distributions.empirical_distribution import ECDF
from copulae1 import *
from KDEs import *
from toolbox import *
import warnings
import itertools
import os
warnings.filterwarnings("ignore")

data = pd.read_csv('../processed_data/btc_future_crix.csv')
brr = np.array(data.return_brr)
btc = np.array(data.return_btc)

In [2]:
import statsmodels.api as sm

In [3]:
sm.stats.acorr_ljungbox(brr)

(array([ 6.24352807,  8.45597587,  8.49126712,  8.49191629,  8.5546366 ,
        10.33457538, 11.28726537, 11.854947  , 12.05304258, 16.08080687,
        19.59287023, 19.67419169, 20.68562563, 20.75289405, 23.49325692,
        25.51691808, 26.28357683, 26.65743642, 27.22554415, 27.73265788,
        28.02707535, 28.03583655, 28.73469728, 29.5374234 , 30.73974366,
        30.84769411, 30.99720306, 31.52950466, 32.1013097 , 32.86352161,
        33.65391704, 34.96667057, 35.39905491, 38.26526729, 38.87466696,
        38.97325044, 38.97986124, 42.46698733, 43.49752294, 43.59652247]),
 array([0.01246479, 0.0145817 , 0.03687828, 0.07513264, 0.12820206,
        0.11125115, 0.12657023, 0.15779408, 0.21033551, 0.09734246,
        0.05124676, 0.07350566, 0.07938383, 0.10813458, 0.07421385,
        0.06121589, 0.0694467 , 0.08564869, 0.09950826, 0.11588051,
        0.13938511, 0.17449659, 0.18926732, 0.20055892, 0.19778174,
        0.23399057, 0.27125346, 0.2940768 , 0.31544402, 0.32849558,
      

In [4]:
sm.stats.acorr_ljungbox(btc)

(array([ 0.03978664,  0.70601303,  0.7100627 ,  0.84715364,  0.94430556,
         2.70260567,  3.49330756,  3.83793776,  4.17816338,  6.71130205,
         6.72623087,  8.5366241 ,  8.6187011 ,  9.70319105, 11.67149359,
        12.52989316, 12.53017405, 12.94906112, 13.30201168, 13.34097078,
        13.71589495, 13.77340488, 13.96701409, 14.02548744, 14.13967569,
        14.16001324, 14.47583894, 16.56019834, 16.98372802, 16.98670837,
        18.96928075, 25.15526013, 25.15900189, 27.06312435, 27.57196876,
        27.57701464, 28.1495539 , 28.79734004, 28.8104951 , 28.9601477 ]),
 array([0.84189833, 0.70257262, 0.87083459, 0.932017  , 0.96693168,
        0.84513943, 0.83593383, 0.87144117, 0.8992996 , 0.75238968,
        0.82080078, 0.74191601, 0.80109303, 0.78354574, 0.70370491,
        0.70676912, 0.7670257 , 0.79459025, 0.8227576 , 0.86227987,
        0.88149059, 0.9093259 , 0.92781193, 0.94607263, 0.95924281,
        0.97083123, 0.97616011, 0.95677798, 0.96243336, 0.97273371,
      

In [5]:
sm.stats.acorr_ljungbox(np.abs(brr))

(array([ 8.32625799, 17.61510018, 30.74040206, 39.79976293, 52.33683484,
        64.37987188, 65.42999862, 67.21210571, 70.01420997, 71.54606936,
        72.3620299 , 74.72713945, 75.03665941, 77.56111367, 84.65322922,
        85.62744107, 85.66777027, 85.67715634, 85.81478776, 86.1369156 ,
        89.19001825, 89.93812484, 91.1669568 , 92.17744625, 92.35315097,
        92.51403519, 93.31676505, 93.40673007, 94.88894145, 95.17812107,
        95.36974595, 95.37004445, 95.39252412, 95.53456391, 95.54601102,
        95.55585875, 95.630925  , 96.01076163, 96.33743979, 96.37056028]),
 array([3.90760680e-03, 1.49599312e-04, 9.64043330e-07, 4.76140487e-08,
        4.60128423e-10, 5.77384807e-12, 1.23242570e-11, 1.75990454e-11,
        1.51295553e-11, 2.22776552e-11, 4.33466897e-11, 4.13737111e-11,
        9.37107380e-11, 7.99660416e-11, 9.74955111e-12, 1.58562200e-11,
        3.71404540e-11, 8.54482986e-11, 1.81317571e-10, 3.48297809e-10,
        2.22554121e-10, 3.51142621e-10, 4.52436349e-10

In [6]:
sm.stats.acorr_ljungbox(np.abs(btc))

(array([ 7.66888624, 22.05732143, 38.37599497, 42.57902535, 50.70296336,
        54.65073552, 55.1533965 , 57.58958516, 57.72835002, 59.01467669,
        59.53761035, 64.49477378, 64.70901142, 66.10942009, 72.05252489,
        72.36786867, 72.46616379, 72.71059138, 73.27069716, 73.30515837,
        73.60576798, 73.70075843, 73.71141581, 75.01633829, 75.19517951,
        77.88438171, 78.35101884, 80.02516612, 83.75082511, 83.77092244,
        85.73720994, 86.40030429, 86.4014853 , 86.42569645, 87.11020531,
        87.12159293, 90.70034181, 90.77589628, 91.70214831, 92.56880614]),
 array([5.61811246e-03, 1.62298127e-05, 2.35305913e-08, 1.26526850e-08,
        9.94934380e-10, 5.45262515e-10, 1.39012365e-09, 1.38149156e-09,
        3.66461313e-09, 5.56478866e-09, 1.12983674e-08, 3.37991553e-09,
        7.44585730e-09, 9.68976419e-09, 1.92001402e-09, 3.82629760e-09,
        8.07911989e-09, 1.56346297e-08, 2.60849821e-08, 5.21039389e-08,
        9.18098377e-08, 1.70910431e-07, 3.20804936e-07